#!/usr/bin/env python3
"""Split dist/sr.js into a homepage core bundle and a deferred rest bundle.

  python3 tools/split-bundle.py

Reads  dist/sr.js               (129 snippets, each headed by `/* [n] name */`)
       dist/homepage-core.json  (list of '[num] name' snippet headers that act on the homepage)
Writes dist/sr.core.min.js      (bootstrap + core snippets, original order; loaded on EVERY page by a
                                 static <script async> tag — the bootstrap loads sr.rest.min.js: at once on
                                 inner pages, after load/first interaction on the homepage)
       dist/sr.rest.min.js      (everything else, original order)

The core list was measured on 28 Sep 2026 by running the live homepage in headless Chromium with
every snippet instrumented (see dist/README.md "Homepage split"). Re-measure it whenever a snippet
is added that should paint on the homepage — an unlisted snippet still runs on the homepage, just
after the load event instead of immediately.
"""
import json, re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / 'dist' / 'sr.js').read_text(encoding='utf-8')
core_keys = set(json.loads((root / 'dist' / 'homepage-core.json').read_text()))

parts = re.split(r'(/\* \[(\d+)\] ([^*]*?) \*/\n)', src)
blocks = [(int(parts[i + 1]), parts[i + 2].strip(), parts[i + 3]) for i in range(1, len(parts), 4)]
assert len(blocks) > 100, 'unexpected sr.js layout'

core, rest = [], []
for k, (num, name, body) in enumerate(blocks):
    key = '[%d] %s' % (num, name)
    (core if key in core_keys else rest).append('/* %s */\n%s' % (key, body.strip() + '\n'))
found = {k.split(' */')[0].lstrip('/* ') for k in core}
assert all(any(c.startswith('/* ' + key + ' */') for c in core) for key in core_keys), 'core snippet names in homepage-core.json not all found in sr.js'


idle_keys = set(json.loads((root / 'dist' / 'inner-idle.json').read_text()))
page = [c for c in rest if c.split(' */')[0][3:] not in idle_keys]
idle = [c for c in rest if c.split(' */')[0][3:] in idle_keys]

# Bootstrap: homepage -> rest after load/first interaction (unchanged).
# Town, search, venue, food-and-drink and machine pages -> sr.page.min.js now (the snippets that do work there,
#   measured with V8 coverage 28 Sep 2026, see dist/README.md), sr.idle.min.js after load/first interaction.
# Every other page -> full sr.rest.min.js at once, as before.
BOOT = """/* [0] Spin Raiders rest-bundle bootstrap (generated) */
(function(){try{var s=document.currentScript,b=s&&s.src?s.src.slice(0,s.src.lastIndexOf("/")+1):"";if(!b)return;var L={};function J(f){if(L[f])return;L[f]=1;var e=document.createElement("script");e.src=b+f;e.async=false;e.fetchPriority="high";document.head.appendChild(e)}function later(f){var d=0;function R(){if(d)return;d=1;J(f)}function A(){setTimeout(R,1500)}if(document.readyState==="complete")A();else addEventListener("load",A);["pointerdown","keydown","touchstart"].forEach(function(t){addEventListener(t,R,{once:true,passive:true})})}var p=location.pathname,q=location.search;if(p==="/"&&!q)later("sr.rest.min.js");else if(/^\\/(destination\\/[^/]+\\/?$|search\\/?$|arcade-venues\\/|food-and-drink\\/|classic-fruit-machine-archive-1\\/)/.test(p)&&!/[?&](view|sr|raidertube|explore|report)=/.test(q)){J("sr.page.min.js");later("sr.idle.min.js")}else J("sr.rest.min.js")}catch(e){console.warn("SR bootstrap failed",e)}})();
"""

hdr = '/* Spin Raiders %s bundle — generated by tools/split-bundle.py from dist/sr.js, %d snippets */\n'
(root / 'dist' / 'sr.core.min.js').write_text(hdr % ('homepage core', len(core)) + BOOT + ''.join(core), encoding='utf-8')
(root / 'dist' / 'sr.rest.min.js').write_text(hdr % ('deferred rest', len(rest)) + ''.join(rest), encoding='utf-8')
(root / 'dist' / 'sr.page.min.js').write_text(hdr % ('inner page', len(page)) + ''.join(page), encoding='utf-8')
(root / 'dist' / 'sr.idle.min.js').write_text(hdr % ('inner idle', len(idle)) + ''.join(idle), encoding='utf-8')
print('page', len(page), 'snippets', sum(map(len, page)), 'bytes; idle', len(idle), 'snippets', sum(map(len, idle)), 'bytes')
print('core', len(core), 'snippets', sum(map(len, core)), 'bytes;', 'rest', len(rest), 'snippets', sum(map(len, rest)), 'bytes')
