#!/usr/bin/env python3
"""Split dist/sr.js into a homepage core bundle and a deferred rest bundle.

  python3 tools/split-bundle.py

Reads  dist/sr.js               (129 snippets, each headed by `/* [n] name */`)
       dist/homepage-core.json  (list of '[num] name' snippet headers that act on the homepage)
Writes dist/sr.core.min.js      (core snippets, original order)
       dist/sr.rest.min.js      (everything else, original order)

The core list was measured on 28 Sep 2026 by running the live homepage in headless Chromium with
every snippet instrumented (see dist/README.md "Homepage split"). Re-measure it whenever a snippet
is added that should paint on the homepage — an unlisted snippet still runs on the homepage, just
after the load event instead of immediately.
"""
import json, re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / 'dist' / 'sr.js').read_text(encoding='utf-8')
core_keys = set(json.loads((root / 'dist' / 'homepage-core.json').read_text()))

parts = re.split(r'(/\* \[(\d+)\] ([^*]*?) \*/\n)', src)
blocks = [(int(parts[i + 1]), parts[i + 2].strip(), parts[i + 3]) for i in range(1, len(parts), 4)]
assert len(blocks) > 100, 'unexpected sr.js layout'

core, rest = [], []
for k, (num, name, body) in enumerate(blocks):
    key = '[%d] %s' % (num, name)
    (core if key in core_keys else rest).append('/* %s */\n%s' % (key, body.strip() + '\n'))
found = {k.split(' */')[0].lstrip('/* ') for k in core}
assert all(any(c.startswith('/* ' + key + ' */') for c in core) for key in core_keys), 'core snippet names in homepage-core.json not all found in sr.js'

hdr = '/* Spin Raiders %s bundle — generated by tools/split-bundle.py from dist/sr.js, %d snippets */\n'
(root / 'dist' / 'sr.core.min.js').write_text(hdr % ('homepage core', len(core)) + ''.join(core), encoding='utf-8')
(root / 'dist' / 'sr.rest.min.js').write_text(hdr % ('deferred rest', len(rest)) + ''.join(rest), encoding='utf-8')
print('core', len(core), 'snippets', sum(map(len, core)), 'bytes;', 'rest', len(rest), 'snippets', sum(map(len, rest)), 'bytes')
